// Non-custodial local wallet storage. The encrypted backup lives in
// IndexedDB on the user's device. The plaintext keypair lives only in memory
// (session) and is never persisted or sent to any server.

const DB_NAME = 'smpf-wallet';
const STORE = 'wallets';

// Upgraded DB version to 2 to prevent version mismatch errors
function openDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 2);
    
    req.onupgradeneeded = (event) => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) {
        db.createObjectStore(STORE, { keyPath: 'address' });
      }
    };
    
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

export async function saveWallet(address, backup, userId) {
  if (!address) {
    throw new Error('Cannot save wallet: Invalid or missing address.');
  }

  const db = await openDB();
  const tx = db.transaction(STORE, 'readwrite');
  tx.objectStore(STORE).put({
    address,
    backup,
    user_id: userId || null,
    created_date: Date.now(),
  });

  return new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve(true);
    tx.onerror = () => reject(tx.error);
  });
}

// Resolve the current authenticated user's id (or null when not logged in).
// Used to isolate each user's non-custodial wallet on a shared device.
export async function getCurrentUserId() {
  try {
    const { base44 } = await import('@/api/base44Client');
    const u = await base44.auth.me();
    return u?.id || null;
  } catch {
    return null;
  }
}

export async function getWallet(address) {
  // Guard against undefined/null keys being passed to IndexedDB .get()
  if (!address) {
    console.warn('getWallet called without a valid address.');
    return null;
  }

  const db = await openDB();
  const tx = db.transaction(STORE, 'readonly');
  return new Promise((resolve, reject) => {
    const r = tx.objectStore(STORE).get(address);
    r.onsuccess = () => resolve(r.result || null);
    r.onerror = () => reject(r.error);
  });
}

export async function listWallets(userId) {
  const db = await openDB();
  const tx = db.transaction(STORE, 'readonly');
  return new Promise((resolve, reject) => {
    const r = tx.objectStore(STORE).getAll();
    r.onsuccess = () => {
      const all = r.result || [];
      if (!userId) return resolve(all);
      resolve(all.filter((w) => w.user_id === userId || !w.user_id));
    };
    r.onerror = () => reject(r.error);
  });
}

export async function removeWallet(address) {
  if (!address) return false;
  const db = await openDB();
  const tx = db.transaction(STORE, 'readwrite');
  tx.objectStore(STORE).delete(address);
  return new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve(true);
    tx.onerror = () => reject(tx.error);
  });
}

// Wipe ALL local wallet data so the user is forced through onboarding again.
// Used to recover from wallets generated by the broken keypair generator.
export async function clearAllWallets() {
  // 1. Clear the IndexedDB wallet store
  try {
    const db = await openDB();
    const tx = db.transaction(STORE, 'readwrite');
    tx.objectStore(STORE).clear();
    await new Promise((resolve, reject) => {
      tx.oncomplete = () => resolve(true);
      tx.onerror = () => reject(tx.error);
    });
  } catch (e) {
    console.warn('clearAllWallets: IndexedDB clear failed', e);
  }
  // 2. Remove all local keypair payloads (smpf_sk_<email>)
  try {
    const toRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (k && k.startsWith('smpf_sk_')) toRemove.push(k);
    }
    toRemove.forEach((k) => localStorage.removeItem(k));
  } catch (e) {
    console.warn('clearAllWallets: localStorage clear failed', e);
  }
  // 3. Clear the in-memory session
  clearSession();
}

// In-Memory Session Management
let activeSession = null; // { secretKeyB64, address, expiresAt }

export function setSession(secretKeyB64, address, ttlMs = 5 * 60 * 1000) {
  activeSession = {
    secretKeyB64,
    address,
    expiresAt: Date.now() + ttlMs,
  };
}

export function getSession() {
  if (!activeSession) return null;
  if (Date.now() > activeSession.expiresAt) {
    activeSession = null;
    return null;
  }
  return activeSession;
}

export function clearSession() {
  activeSession = null;
}